<?xml version="1.0" encoding="utf-8"?><Database Name="CMS" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DRAGANRUSNOV-PC\SQLEXPRESS;Initial Catalog=CMS;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Registered" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_Role" Member="Roles" ThisKey="ID" OtherKey="AccountID" Type="Role" />
      <Association Name="Status_Account" Member="Status" ThisKey="StatusID" OtherKey="ID" Type="Status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Status" Member="Status">
    <Type Name="Status">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Status_Account" Member="Accounts" ThisKey="ID" OtherKey="StatusID" Type="Account" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SecurityRole" Type="SecurityRole" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_Role" Member="Account" ThisKey="AccountID" OtherKey="ID" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Body" Member="Bodies">
    <Type Name="Body">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WebPageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HTML" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="WebPage_Body" Member="WebPage" ThisKey="WebPageID" OtherKey="ID" Type="WebPage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Header" Member="Headers">
    <Type Name="Header">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WebPageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MoviePath" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ImagePath" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="WebPage_Header" Member="WebPage" ThisKey="WebPageID" OtherKey="ID" Type="WebPage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NavigationLink" Member="NavigationLinks">
    <Type Name="NavigationLink">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WebPageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Section_NavigationLink" Member="Section" ThisKey="SectionID" OtherKey="ID" Type="Section" IsForeignKey="true" />
      <Association Name="WebPage_NavigationLink" Member="WebPage" ThisKey="WebPageID" OtherKey="ID" Type="WebPage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Section" Member="Sections">
    <Type Name="Section">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TabID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="URLTitle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Section_NavigationLink" Member="NavigationLinks" ThisKey="ID" OtherKey="SectionID" Type="NavigationLink" />
      <Association Name="Tab_Section" Member="Tab" ThisKey="TabID" OtherKey="ID" Type="Tab" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tab" Member="Tabs">
    <Type Name="Tab">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="URLTitle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FAQPageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Tab_Section" Member="Sections" ThisKey="ID" OtherKey="TabID" Type="Section" />
      <Association Name="WebPage_Tab" Member="WebPage" ThisKey="FAQPageID" OtherKey="ID" Type="WebPage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Template" Member="Templates">
    <Type Name="Template">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Template_WebPage" Member="WebPages" ThisKey="ID" OtherKey="TemplateID" Type="WebPage" />
    </Type>
  </Table>
  <Table Name="dbo.Type" Member="Types">
    <Type Name="Type">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Type_Sidebar" Member="Sidebars" ThisKey="ID" OtherKey="TypeID" Type="Sidebar" />
    </Type>
  </Table>
  <Table Name="dbo.WebPage" Member="WebPages">
    <Type Name="WebPage">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="URLTitle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsHomePage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="WebPage_Body" Member="Bodies" ThisKey="ID" OtherKey="WebPageID" Type="Body" />
      <Association Name="WebPage_Header" Member="Headers" ThisKey="ID" OtherKey="WebPageID" Type="Header" />
      <Association Name="WebPage_NavigationLink" Member="NavigationLinks" ThisKey="ID" OtherKey="WebPageID" Type="NavigationLink" />
      <Association Name="WebPage_Tab" Member="Tabs" ThisKey="ID" OtherKey="FAQPageID" Type="Tab" />
      <Association Name="WebPage_Document" Member="Documents" ThisKey="ID" OtherKey="WebPageID" Type="Document" />
      <Association Name="WebPage_Sidebar" Member="Sidebars" ThisKey="ID" OtherKey="WebPageID" Type="Sidebar" />
      <Association Name="WebPage_Employee" Member="Employees" ThisKey="ID" OtherKey="WebPageID" Type="Employee" />
      <Association Name="Template_WebPage" Member="Template" ThisKey="TemplateID" OtherKey="ID" Type="Template" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Category_Document" Member="Documents" ThisKey="ID" OtherKey="CategoryID" Type="Document" />
    </Type>
  </Table>
  <Table Name="dbo.Document" Member="Documents">
    <Type Name="Document">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Source" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Thumb" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WebPageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_Document" Member="Category" ThisKey="CategoryID" OtherKey="ID" Type="Category" IsForeignKey="true" />
      <Association Name="WebPage_Document" Member="WebPage" ThisKey="WebPageID" OtherKey="ID" Type="WebPage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sidebar" Member="Sidebars">
    <Type Name="Sidebar">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WebPageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Source" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Thumb" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsOverlay" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Type_Sidebar" Member="Type" ThisKey="TypeID" OtherKey="ID" Type="Type" IsForeignKey="true" />
      <Association Name="WebPage_Sidebar" Member="WebPage" ThisKey="WebPageID" OtherKey="ID" Type="WebPage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Photo" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="WebPageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="WebPage_Employee" Member="WebPage" ThisKey="WebPageID" OtherKey="ID" Type="WebPage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Media" Member="Medias">
    <Type Name="Media">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>